### ISSUE TITLE
Question about your code

### ISSUE THREAD

**Issue by pminervini** [cf020031308/mad-learning#1]
Hi, nice work!

I was reading `citations.py` and I was wondering why there is no `opt.zero_grad()` after `opt.step()` in https://github.com/cf020031308/mad-learning/blob/master/citations.py#L171: is there a particular reason?

Thanks!

**Comment by cf020031308** [comment]
Hi, @pminervini 
I think it is a mistake. `opt.zero_grad()` should be in the loop.
The (AUC, AP) after this change is (96.17%, 94.13%) for Cora, (96.40%, 95.95%) for Citeseer.
I am currently rerunning the experiment on Pubmed.
Thanks for your interest.

**Comment by pminervini** [comment]
Ok, thanks! :)

Since we are at it -- I don't think `adj` should be used within the training loop, since it also contains edges in the validation and test sets: https://github.com/cf020031308/mad-learning/blob/master/citations.py#L215

**Comment by cf020031308** [comment]
L215 is in the evaluation phase, not in the training loop.
And I think it is OK to use `adj` in the training loop to construct negative samples like:
https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/utils/negative_sampling.html#negative_sampling

**Comment by cf020031308** [comment]
> Ok, thanks! :)
> 
> Since we are at it -- I don't think `adj` should be used within the training loop, since it also contains edges in the validation and test sets: https://github.com/cf020031308/mad-learning/blob/master/citations.py#L215

adj should be replaced with mem. I'll check this at tomorrow morning.

**Comment by pminervini** [comment]
> L215 is in the evaluation phase, not in the training loop.
> And I think it is OK to use `adj` in the training loop to construct negative samples like:
> https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/utils/negative_sampling.html#negative_sampling

If `adj` contains validation and test edges, I don't think it's ok to use it to inform the training loop!

**Comment by cf020031308** [comment]
> > L215 is in the evaluation phase, not in the training loop.
> > And I think it is OK to use `adj` in the training loop to construct negative samples like:
> > https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/utils/negative_sampling.html#negative_sampling
> 
> If `adj` contains validation and test edges, I don't think it's ok to use it to inform the training loop!

Hi @pminervini 

You are right. Validation and testing information should not be used in the training loop.
I thought using validation and testing information only to ensure that the randomly sampled edges were really negative is OK.

However, sampling edges randomly for enough times can cover most edges. So in my situation, using validation and testing information to filter samples at every time can be a problem.

And just now I checked the code of negative sampling in SEAL (I am recently reading it):
https://github.com/facebookresearch/SEAL_OGB/blob/master/utils.py#L215
`edge_index` is the training set:
https://github.com/facebookresearch/SEAL_OGB/blob/master/seal_link_pred.py#L400

So `adj` should be replaced with `mem`. Thank you for your helpful points.

**Comment by pminervini** [comment]
@cf020031308 one more thing -- this one can be pretty serious

The graph is undirected, and the same edges appear twice in `(src, dst)`, once as A-B and another time as B-A -- https://github.com/cf020031308/mad-learning/blob/master/citations.py#L101:

```python
In [17]: src, dst = graph.edges()

In [18]: AB = [(s.item(), d.item()) for s, d in zip(src, dst)]

In [19]: BA = [(d.item(), s.item()) for s, d in zip(src, dst)]

In [20]: AB[0]
Out[20]: (0, 633)

In [21]: AB[0] in BA
Out[21]: True
```

so the same edges can be both e.g. in train and validation or test

**Comment by cf020031308** [comment]
Hi @pminervini 
Thank you very much to point this serious problem out. 
This makes `mem` (and the training set) containing also validation and testing information.

I am very sorry to have made this stupid mistake.
I removed those three wrong scores on Cora, Citeseer and Pubmed from Paper With Codes. By the way, the AUC/AP scores after these changes are 88.40/88.04 for Cora, 88.05/89.66 for Citeseer and approximately 94/94 for Pubmed. (As to `ogbl-ddi`, the training edges are provided in the dataset. So it may not suffer from this issue.)
I will check my code again, update my method and correct the errors in my paper next week as soon as possible.
